### ISSUE TITLE
0.59: a slideshow, high ping, messages window. 0.58: low FPS

### ISSUE THREAD

**Issue by esamo** [openlierox/openlierox#783]
Hello again.

I've compiled 0.58 and 0.59 on Linux Ubuntu 14.04 x64 (CPU: 2x 1800 MHz [APU - like CPU + GPU]).

1) OpenLieroX has hard graphics on Linux for some reason. On version 0.58 I can not turn shadows + particles + AA and have smooth game. I can't even have particles alone... But I can play on 0.58 without special effects. On 0.59 I can not play at all since it has 1-2 FPS which comes simply to a slideshow. Local match with CPUs makes no difference.
I'm driving GPU on fglrx-updates which is up-to-date AMD drivers package.

2) 0.59 I have ping 500 ms while on the same server 0.58 has ping 50 ms.

3) 0.59 could use font shadow for a chat and log messages to be readable on same-color surface.

---

Regards & respect.

**Comment by albertz** [comment]
Try playing around with the graphics settings. What are your current settings? Try to enable/disable OpenGL. Try with different bits-per-pixel. And other things.

Also, maybe you get some hints in the log file about some problems. Check `~/.OpenLieroX/logs` (or so).

I'm currently working on some updates on 0.59 which might resolve those problems. You can checkout the `wip` branch. It should compile and run, but it isn't really working yet (work in progress). But you might be able to see whether the graphics run smoother.

**Comment by esamo** [comment]
I feel that OpenGL works better, but I can't tell for sure because in-game FPS is not shown stably. Jumps too fast to read.
Didn't see a difference between various color depth, so I set it to auto.

What about much higher ping on 0.59?

Another issue - at the menu FPS are updated only when I move a mouse pointer, which can be related to speedy & shaky pointer movement (on my touchpad on Ubuntu).

Attaching 2 fresh log files from 0.59.
https://docs.google.com/file/d/0B9qkeujf78R0TEJaQnk2SXNreXM/edit
https://docs.google.com/file/d/0B9qkeujf78R0MjROajA0QW95dDg/edit

---

`wip` compilation have failed. Source: `git clone -b wip https://github.com/albertz/openlierox.git`

```
esamo@Es-mob:~/Games/OpenLieroX_wip_git/openlierox$ cmake .
SYSTEM_DATA_DIR = /usr/share/games
DEBUG = ON
DEDICATED_ONLY = OFF
G15 = OFF
X11 = ON
HAWKNL_BUILTIN = ON
LIBZIP_BUILTIN = OFF
LIBLUA_BUILTIN = ON
STLPORT = OFF
GCOREDUMPER = OFF
HASBFD = ON
BREAKPAD = OFF
LINENOISE = ON
CMAKE_C_COMPILER = /usr/bin/cc
CMAKE_C_FLAGS = 
CMAKE_CXX_COMPILER = /usr/bin/c++
CMAKE_CXX_FLAGS = 
MINGW_CROSS_COMPILE = OFF
OLX_VERSION = 0.59_beta10
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   signals
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/esamo/Games/OpenLieroX_wip_git/openlierox
esamo@Es-mob:~/Games/OpenLieroX_wip_git/openlierox$ make
Scanning dependencies of target openlierox
[  0%] Building CXX object CMakeFiles/openlierox.dir/src/main.o
c++: error: sh:: Nie ma takiego pliku ani katalogu
c++: error: 1:: Nie ma takiego pliku ani katalogu
c++: error: sdl2-config:: Nie ma takiego pliku ani katalogu
c++: error: not: Nie ma takiego pliku ani katalogu
c++: error: found: Nie ma takiego pliku ani katalogu
make[2]: *** [CMakeFiles/openlierox.dir/src/main.o] Błąd 1
make[1]: *** [CMakeFiles/openlierox.dir/all] Błąd 2
make: *** [all] Błąd 2
```

---

Regards & respect

**Comment by esamo** [comment]
0.59: Right, another log, this one is created from a game with local match started and quit. FPS 1/1 or 1/0. Also maps are loading waaay too long for such a simple game :) .
https://docs.google.com/file/d/0B9qkeujf78R0eFpJQl9YRnN4NFk/edit

**Comment by albertz** [comment]
About the problem with `wip`: You also need to install  libsdl2-dev and libsdl2-image-dev.

In all cases: Try with Debug disabled (`cmake -DDEBUG=Off .`). And then recompile (`make`). That should make things faster (not sure if fast enough).

**Comment by esamo** [comment]
`wip`

```
[  6%] Building CXX object CMakeFiles/openlierox.dir/src/client/Clipboard.o
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:
In member function ‘void XHelper::acquire()’:
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:140:25:
error: ‘SDL_GetWMInfo’ was not declared in this scope
    SDL_GetWMInfo(&wmInf_);
                         ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:142:20:
error: ‘struct SDL_SysWMinfo::<anonymous union>::<anonymous>’ has no member
named ‘lock_func’
    wmInf_.info.x11.lock_func();
                    ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:
In member function ‘void XHelper::release()’:
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:150:20:
error: ‘struct SDL_SysWMinfo::<anonymous union>::<anonymous>’ has no member
named ‘unlock_func’
    wmInf_.info.x11.unlock_func();
                    ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:
In function ‘void Clipboard_handleSysWmEvent(const SDL_Event&)’:
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/Clipboard.cpp:215:33:
error: ‘SDL_SysWMmsg’ has no member named ‘event’
  XEvent& xev = event.syswm.msg->event.xevent;
                                 ^
make[2]: *** [CMakeFiles/openlierox.dir/src/client/Clipboard.o] Błąd 1
make[1]: *** [CMakeFiles/openlierox.dir/all] Błąd 2
make: *** [all] Błąd 2
esamo@Es-mob:~/Games/OpenLieroX_wip_git/openlierox$ cmake .
SYSTEM_DATA_DIR = /usr/share/games
DEBUG = Off
DEDICATED_ONLY = OFF
G15 = OFF
X11 = ON
HAWKNL_BUILTIN = ON
LIBZIP_BUILTIN = OFF
LIBLUA_BUILTIN = ON
STLPORT = OFF
GCOREDUMPER = OFF
HASBFD = ON
BREAKPAD = OFF
LINENOISE = ON
CMAKE_C_COMPILER = /usr/bin/cc
CMAKE_C_FLAGS =
CMAKE_CXX_COMPILER = /usr/bin/c++
CMAKE_CXX_FLAGS =
MINGW_CROSS_COMPILE = OFF
OLX_VERSION = 0.59_beta10
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   signals
--   system
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/esamo/Games/OpenLieroX_wip_git/openlierox
```

---

`0.59 DEBUG=Off`

Mouse - outside of a match - very nice control.
Touchpad - outside of a match - still hardly possible to navigate.

FPS: much better, however still ridiculously low (19-23 minimal settings,
match without any weapons), OpenGL even worse, auto color bit. I can barely
BUT -play- 3D games on Windows partition example: Skyrim, Age of Wonders,
Eador Masters of the Broker World. So reasonably surprised for so low FPS
2D shooter :), but that's on Linux .

---

Pozdrawiam / Regards & respect,
Patryk Frey

---

**Comment by albertz** [comment]
I pushed an update to `wip`.

**Comment by esamo** [comment]
`wip`

```
[ 25%] Building CXX object CMakeFiles/openlierox.dir/src/client/NotifyUser.o
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp: In function ‘void x11_SetDemandsAttention(bool)’:
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:38:21: error: ‘SDL_GetWMInfo’ was not declared in this scope
  SDL_GetWMInfo(&info);
                     ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:40:16: error: ‘struct SDL_SysWMinfo::<anonymous union>::<anonymous>’ has no member named ‘lock_func’
  info.info.x11.lock_func();
                ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:50:35: error: ‘struct SDL_SysWMinfo::<anonymous union>::<anonymous>’ has no member named ‘wmwindow’
  e.xclient.window = info.info.x11.wmwindow;
                                   ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:59:56: error: ‘struct SDL_SysWMinfo::<anonymous union>::<anonymous>’ has no member named ‘wmwindow’
   XChangeProperty(info.info.x11.display, info.info.x11.wmwindow, wmState, XA_ATOM, 32, PropModeReplace, (unsigned char *)&demandsAttention, 1);
                                                        ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:63:16: error: ‘struct SDL_SysWMinfo::<anonymous union>::<anonymous>’ has no member named ‘unlock_func’
  info.info.x11.unlock_func();
                ^
make[2]: *** [CMakeFiles/openlierox.dir/src/client/NotifyUser.o] Błąd 1
make[1]: *** [CMakeFiles/openlierox.dir/all] Błąd 2
make: *** [all] Błąd 2
esamo@Es-mob:~/Games/OpenLieroX_wip_git/openlierox$ cmake .
SYSTEM_DATA_DIR = /usr/share/games
DEBUG = Off
DEDICATED_ONLY = OFF
G15 = OFF
X11 = ON
HAWKNL_BUILTIN = ON
LIBZIP_BUILTIN = OFF
LIBLUA_BUILTIN = ON
STLPORT = OFF
GCOREDUMPER = OFF
HASBFD = ON
BREAKPAD = OFF
LINENOISE = ON
CMAKE_C_COMPILER = /usr/bin/cc
CMAKE_C_FLAGS = 
CMAKE_CXX_COMPILER = /usr/bin/c++
CMAKE_CXX_FLAGS = 
MINGW_CROSS_COMPILE = OFF
OLX_VERSION = 0.59_beta10
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   signals
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/esamo/Games/OpenLieroX_wip_git/openlierox
```

---

Regards & respect

**Comment by albertz** [comment]
And again, I pushed an update to `wip`. :p

**Comment by esamo** [comment]
`wip`

```
[  1%] Building CXX object CMakeFiles/openlierox.dir/src/client/NotifyUser.o
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp: In member function ‘virtual Result NotifyUserOnEvent()::SetDemandsAttentionAction::handle()’:
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:112:32: error: ‘x11_SetDemandsAttention’ was not declared in this scope
    x11_SetDemandsAttention(true);
                                ^
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp: In member function ‘virtual Result ClearUserNotify()::ClearDemandsAttentionAction::handle()’:
/home/esamo/Games/OpenLieroX_wip_git/openlierox/src/client/NotifyUser.cpp:136:33: error: ‘x11_SetDemandsAttention’ was not declared in this scope
    x11_SetDemandsAttention(false);
                                 ^
make[2]: *** [CMakeFiles/openlierox.dir/src/client/NotifyUser.o] Błąd 1
make[1]: *** [CMakeFiles/openlierox.dir/all] Błąd 2
make: *** [all] Błąd 2
esamo@Es-mob:~/Games/OpenLieroX_wip_git/openlierox$ cmake .
SYSTEM_DATA_DIR = /usr/share/games
DEBUG = Off
DEDICATED_ONLY = OFF
G15 = OFF
X11 = ON
HAWKNL_BUILTIN = ON
LIBZIP_BUILTIN = OFF
LIBLUA_BUILTIN = ON
STLPORT = OFF
GCOREDUMPER = OFF
HASBFD = ON
BREAKPAD = OFF
LINENOISE = ON
CMAKE_C_COMPILER = /usr/bin/cc
CMAKE_C_FLAGS = 
CMAKE_CXX_COMPILER = /usr/bin/c++
CMAKE_CXX_FLAGS = 
MINGW_CROSS_COMPILE = OFF
OLX_VERSION = 0.59_beta10
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   signals
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/esamo/Games/OpenLieroX_wip_git/openlierox
```

---

0.59 was compiled with X11.

---

Regards & respect.

**Comment by albertz** [comment]
And I pushed another update to `wip`.

**Comment by esamo** [comment]
`wip` compiled and run.

1) Touchpad - finally able to navigate! Success!

2) FPS - still not much 17-21, minimal graphics settings and no matter OpenGL. Something is not right :( . Maybe GPU is not being used?

3) GUI feels smoother.

4) Mouse can go waaay far over OpenLieroX screen (it is not pulled right away from the edge but has to 'come back' from 'not existing' area of screen when moved there.

5) I have uglier GUI compared to `0.59` or `0.58`, this may be no anti aliasing or resolution maybe?

Well I see step forward :) .

---

Regards & respect.

**Comment by albertz** [comment]
Good to hear that. I have now deleted the `wip` branch and merged everything into the `0.59` branch.

I also fixed the mouse coordinates somewhat in full screen mode, but if you got some letterboxing area (if your screen does not have a 4x3 ratio), I think it can still go out of the screen.

Also, fullscreen should look better now (linear instead of nearest interpolation).

**Comment by esamo** [comment]
Fullscreen is great.

I'm on max graphics settings and FPS are 30 for Castle Strike, lower for bigger maps (20 for dm1[Tee], also loading ~10 sec).

But shadows are totally gone!

When I don't select any player to local match I go alert but the match starts anyway and results game crash.

---

Regards & respect.
